theme: osuny
_merge: deep
params:
  plausible: re-akt.ch
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  logo:
    footer: "/assets/images/logo-blanc.svg"
  pages:
    index:
      truncate_description: 0