theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: re-akt.ch
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    footer: "/assets/images/logo-blanc.svg"
  pages:
    index:
      truncate_description: 0